# permissions for end users to edit imagerepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-reflector-imagerepository-editor-role
rules:
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagerepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagerepositories/status
  verbs:
  - get