# FluxCD Kustomization for flask_404_app
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app-404
  namespace: flux-system
spec:
  interval: 1m0s
  path: ../../base/flask_404_app
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
