apiVersion: v1
kind: Service
metadata:
  name: flask-404-service
  namespace: flask-404-app
  labels:
    app: flask-404
    environment: production
    team: devops
    version: v1.0.0
spec:
  selector:
    app: flask-404
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
