---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: docker.io
  namespace: smart-ai
spec:
  encryptedData:
    .dockerconfigjson: AgAcKRMO3OGYIfxgxo66hOCYkp3SjLuiPKazWT0qSSx0lgNPvEmaGa8riZRB9V8LY2q1Chnwfm5zVYY/vZSqR62QDdRSucL3Vf3EXWXpZU3Gang431Fw6AVzZkd92AdcOGMWm6dTrrYgSG1NecgV1EFaM4bpl8Fgf3X+5UgUFjW436uQ3PwxbCv61zBH+VSbaALGjhHNo4sir8QcyCjMEIiNAkWTso3Q1qy2u9XblSUmBXP/OihjpPDEjLmfjbWSShLBGtdAXUy75OQ2YB40iVxSGd578/FuZe126k104SLbFwyDI0ot7adQ54XtOBDDflFiBZDkYrx1pXjvZjAiiRAymvzMYivw/yA34qMqLVf5NCK+DMno4KgR9ZWneHQ+vVBEceS9kH9BlGF8EuBHFqYpxDyfZp41XQeLm9/8mlfGkVtcb3nosGVh1LjtCI3JtaxT4sVqE76XKqw/D2zFny14jHWAtuAy56O9+69EECTLsUzglIWuBKQ9enlY+3K/7uzrVQlLNywtVsFvEW3Q490cv5ZOjQXtq3gH9v9TLRpwgYjax3Lm5oagKsB3zykknjTHu8l0pU++JOxWuQWLZBA9od2fTd7vdqHk3KAzcboSwac3CwPqmV4sLttOB+DstxvNOqEcUPm75Vtl5T+wQjdUHXw1XJZZ9KqND5ZI023hSWdJOayA66DBS4SWd21SVtiQR9TNlSk56g0DhvYaymdFw67k2utHIZAAf0R253yDdtlRGN4hnuc7TSYOJNdY9wJLhauX/L1ECjte4a1h89IM3BfqcF6ZDAQKXTK0h/1OshTomGKOzH+deq1Cz8eW+WkP0kaKb2VkV5rAAGrCOJ4tTusqaMmdHnO7roaEZzF+z1GXJaXUJYkDW2Rg2SIcwdoDoYqONfHyUKdAIfaALK2RO0wHYKT46ifr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: docker.io
      namespace: smart-ai
    type: kubernetes.io/dockerconfigjson
