apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - image-policy.yaml
  - image-repo.yaml
  - image-update-automation.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
  - docker.io-sealed.yaml
namespace: smart-ai
commonLabels:
  app: smart-ai
  app.kubernetes.io/name: smart-ai
  app.kubernetes.io/instance: smart-ai
  app.kubernetes.io/component: smart-ai
  app.kubernetes.io/part-of: smart-ai
  app.kubernetes.io/managed-by: kustomize

