apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-reflector-leader-election-rolebinding
  namespace: kommander-flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-reflector-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system