apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: kommander-flux
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: ./
  sourceRef:
    kind: OCIRepository
    name: capacitor
