apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-ingress
spec:
  releaseName: istio-ingressgateway
  chart:
    spec:
      chart: gateway
      version: 1.22.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  values: {}
