apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  releaseName: kiali-server
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  interval: 5m
  values: {}
