apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ../../../helm/gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fluxcd
      version: "*"
  install:
    createNamespace: true
  interval: 30s
  targetNamespace: gitea
