apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app-404
  namespace: kommander-flux
spec:
  force: false
  interval: 1m0s
  path: ./clusters/prod/apps/flask_404_app/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
