apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goharbor
  namespace: kommander-flux
spec:
  chart:
    spec:
      chart: ./clusters/prod/helm/harbor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fluxcd
      version: "1.17.0"
  install:
    createNamespace: true
  interval: 30s
  targetNamespace: harbor
