apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-loki
  namespace: kommander-flux
spec:
  chart:
    spec:
      chart: ./clusters/prod/helm/loki-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fluxcd
      version: "*"
  install:
    createNamespace: true
  interval: 30s
  targetNamespace: loki
