apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  finalizers:
    - finalizers.fluxcd.io
  generation: 2
  name: jenkins
  namespace: kommander-flux
spec:
  force: false
  interval: 1m0s
  path: ./clusters/prod/apps/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
