---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: smart-ai
  namespace: kommander-flux
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: lopchanmangal5@gmail.com
        name: LinuxNerdBTW
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: fluxcd
  update:
    path: ./clusters/prod/apps/chatbot/manifests/
    strategy: Setters
