---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-404-app
  namespace: kommander-flux
spec:
  interval: 1m0s
  path: ./clusters/prod/apps/flask_404_app
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
