# Kustomization for Image Automation Controller
resources:
  - ../../image-automation-controller/leader-election-role-binding.yaml
  - ../../image-automation-controller/leader-election-role.yaml
  - ../../image-automation-controller/role-binding.yaml
  - ../../image-automation-controller/role.yaml
