---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker.io
spec:
  encryptedData:
    .dockerconfigjson: AgBb5Pdokn91CIKMoPPz4ohINoVahC0+ZFoHeqYnEPm+1d5oy/2KrOJPLpUIqMGT07ySqPKqzkunAE8vCJPiHmLXzGR/RkWi893XpQP8o4f3fuJuQZTkHYT3amXZYAQTSnsyVXyhgxMVa9k56JhNRXwUssVOFfMnHI+F4XT3JBTo789lopEahXp9P0cCPS8aWpqu2s6sZG9KS+vaP11TT2dKfS1kotqOQGx6twm0Z33QAkXNWQC/7YL/9mTqHN/IYzAZdxOrdZ7/E7TcwZ1Q1M4BRkGJcXr8piU7ZWc+WpDQjC7uBPYamXK9SF0G8nXRwRY3So9CZicj7ldF4ooiCb7Rzc+dbm8QRzl5WAFPm1EAxzomF+dL9WUrZtx6nbkubVntWP8qsJhY6qxp3reVB1afqBOOE3U0sG84KtlcYo+mp3Xi+yZJMZoRfXFjd/39r065Mu8eNGuObPGV1FRdEjCf0Pyd5SdQqpkv9vKgkgV2P2RpX4gHj87oZUJC7l8iKghwDMBZdZxbRDsUnYiHML0tVzAjpMaPO4O3UsRc+JQQpfT/Cdbtcm6I3ewqRMyPSNlNt3cepu0gNdMoXvf6F7+6SpdqJH3G8Yqo/DHUycG1EFuo+ujDsdmTHmxk6wS2SJXfmjd0pXTFewh+3hcs1GiFnWJPGCL2x4sfBAYYMKe8i0mXQouyAmRamUMAETi4L+HZ898JCNPP6EpgC4kz5LeSk9ww7aAJDhlh4Xvy6Z7/vhuB266ezcSwbOCiFY79PO/kPRO6u691ZEw9d+4EAQqWFp66B9S0VlO0MUlhkl+k0GG6oMJXinNTPOcg9xqiaxoVnO8JKxDZ//X7K3JIIM0cQugMMcjcKaPiCuwcRp4KI1Dm5cIpnMgaCuMCKHlXXI9tj0wAlCCzZNjbYoZzszcpZlV6iGMKskoZ
  template:
    metadata:
      creationTimestamp: null
      name: docker.io
    type: kubernetes.io/dockerconfigjson
