---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: docker.io
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgA2pQY0quVUEjAUlx4e6Q9Yc95Wg2H6Jz0b7yfFg77yWq5qeDiQuv+XGygnGbdeXXMey3UIKqlJCCTEf1iMvG4Tr9idIwkAPuMhyoc7yVc45bq1w5473fOUdXI2xL/NrLOkw3BPT3sSsETk8iXaGDpIcAswHbNs2vPfkiGEOJ7UltpldT8faJbFts2TM+S8tRrVSPJVLWHOTSzdoOchYuNSIJ1+n8apNVQDAOnBkYXu+DToHsUbZtyVZs3ku5fKaY1+KtiiYc5QF1ljwUGHHvofHMFVRdtsawTUWJlArgIsrNlUmYNhCH6t2w3SSVgnIeXWgU/2wFciE6x2s33cf8iuwYf7uGSWN+Ih3X8pDAuImmJJmzF+LA/ZtgzOSxC8XMoCKoV8lzNKnz5ZOJWlO0emArtf7Gu2z8G4JKGv3Wk3dlksb/uc3gelTOLMOcGOlkVApC7FGSFtC85dVHCdeyW9F5fapCU7eahi5TsBE935zg9zbYFy3QVQySB0MmTwoGghkoDH8/wEKyOQxAIotglGqQllhoJiJAUkECR0z21pKm7EPNC3Yzac/70WLTusQEbYibAaGOTukckh1H21v6PvwOva2DDX04QwY8r97Co+Qs8Hf4R1nsiBDQpE62/WOwFXdm0lVo1sEOoRoD3NPfz6ZJOFsATSMN81ifufwyyTfBrWIpN+IEJVtfmGEI8zB5vgoDAJhE8YQiY9usHt51Jl2+50jj9V9TdDgBH+d3/eG5Snazi2oJjObpOtfyKMQ67T6QT7cz2DJ0mf3THvnQqVp0dVwMvemLJmrcNKhuUbfRjYbggIBVsA63VcCMcPosQWfED9V0cTSARgNFerQFEOJ+xccGliaNHRyP9xh+ddLDyLM//Z0QgDV3NqSIRKZOGeKWifImuXxT4FPetKlgaSJQwc92l8NmTX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: docker.io
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
