---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: docker.io
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgAWgRp23nl2WPgheW4SpbxLZ5K2S6vzOYN3Ps79bRZvv5HebCOjDlxYgKJvDRwD5jcwyuZEznDiLfzRVANuqTAO9kUcsSGqwvwMKGopzaISZJEAj0QATs9cfAg2D0FHs1wxo0s9qiC5W8IEUZFN3raXop23laGb7bZRl9BV2W4pzGPapLsrqfZmYtx+IklWP7/7gKOQbA/J+tOfnUNwmol5ouf+0X+AYv1UI6IJ5NsEF2WfbLW6oUd0/+d/C3kUGSxtvHVIHzNMq5vNmWNedQr8tT+Pbe5+bx43LcLPLwS0SspGmYhQqED19pcn21plGaByYIdxtfaVnaJKVJXCzP9VEVkMzYdVxMQaG1ezFiFDlLSxHudabm3xu9vhqhUQTWgx6SEBRm5RA3m9OaPLBIR5ERhEAU14wMn0mpu7qJtZ0rPASj/uySRywzYk9IvnMEG8Atc+PRFhmGE4YWOTjbZKZHee9xTT8ReYeDjpbFqInA09OOaowpxoBhc5lz3klgVKeBnzJCwWzRhMjPWcoayro/VVF6OA6xJz0hY7Ber2siaNC6/QdwwykHSRLy/zKrgu2CeEX9iI7cOWNekvG6X7z8v6o7HmQL80PXW97ozxtKOI7f0Cax6CQxNtc7uiHsJx1pCa7LMCyOxiIIS0W6UsoGJZKT6ibRGzwoMqVzYKx5iJCXy/MROD5D44c7RCRcEFbblAzCFhwRm1paL3C9sYIQ6TEvxON+CrBpIr23RU/O7zEse5n5IoLLZBkg0SFY3yVu6aqRyYgIYKrZBztkL5Mdbnq5UNBouQBeyXenMO1pMf+elOYgN0CsA6OMPCSlglMvzxsahUMiShtTwNNGMFjpN3ACgOeCu/KobtpYsZdvYVlS+V4LEA9dRq8iW0VlXPsuj+t2Q3MC6YXAo7jnxeaLhH8kLhfTM2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: docker.io
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
