# FluxCD Kustomization for jenkins
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 1m0s
  path: ../../base/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
