apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceAccount.yaml
  - volume.yaml
  - docker.io-sealed.yaml

namespace: jenkins
commonLabels:
  app: jenkins
  app.kubernetes.io/name: jenkins
  app.kubernetes.io/instance: jenkins
  app.kubernetes.io/component: jenkins
  app.kubernetes.io/part-of: jenkins
  app.kubernetes.io/managed-by: kustomize
