apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    some-label: docker-builder
spec:
  imagePullSecrets:
    - name: docker.io
  containers:
    - name: docker
      image: docker:24.0.5-dind
      command: ["/bin/sh", "-c"]
      args:
        - apk add --no-cache git && dockerd-entrypoint.sh
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
    - name: jnlp
      image: jenkins/inbound-agent:latest
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
