apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    some-label: docker-builder
spec:
  imagePullSecrets:
    - name: docker.io
  containers:
    - name: docker
      image: docker:24.0.5-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
