# Chatbot Service to expose
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: smart-ai
  labels:
    app: chatbot
    component: service
    tier: backend
spec:
  selector:
    app: chatbot
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
